[[main]]
  identifier = "about"
  name = "About"
  url = "about"
  weight = 1

[[main]]
  identifier = "archive"
  name = "Archive"
  url = "archive"
  weight = 2

[[main]]
  identifier = "presentation"
  name = "Pt"
  url = "presentation"
  weight = 3

[[main]]
  identifier = "gallery"
  name = "Gallery"
  url = "gallery"
  weight = 4
    
[[main]]
  parent = "gallery"
  name = "Cartoon"
  url = "gallery/cartoon"

[[main]]
  parent = "gallery"
  name = "Photo"
  url = "gallery/photo"

[[main]]
  identifier = "posts"
  name = "Posts"
  url = "posts"
  weight = 5

[[main]]
  identifier = "categories"
  name = "categories"
  url = "categories"
  weight = 6

[[main]]
  identifier = "tags"
  name = "tags"
  url = "tags"
  weight = 7

[[main]]
  identifier = "showcase"
  name = "Showcase"
  url = "showcase"
  weight = 8

[[main]]
  identifier = "publication"
  name = "Pub"
  url = "publication"
  weight = 9